Replace socket2 calls with rustix
smol-rs/async-io pull request #146
Opened 2023-09-07 03:30 UTC by notgull

socket2 is our last libc-using dependency. By replacing it with rustix calls, we can make this crate libc-free.

This doesn't set the inherit disable property on Windows yet, as rustix does not support it.

2023-09-07 11:46 UTC, taiki-e commented on src/lib.rs
> +        Err(rio::Errno::AGAIN) => {}
io::ErrorKind::WouldBlock means both `EAGAIN` and `EWOULDBLOCK`.
https://github.com/rust-lang/rust/blob/f00c1399987c60b4e884afc42f4aa6226855e9ae/library/std/src/sys/unix/mod.rs#L288-L291

2023-09-07 11:46 UTC, taiki-e commented on src/lib.rs
> +        ))]
Do aix and haiku not have cloexec?
socket2 seems to set it on all unix.
https://github.com/rust-lang/socket2/blob/66ed6b055a4352a26ed25e8d01981fb5b555f3d8/src/socket.rs#L780

2023-09-07 11:46 UTC, taiki-e commented on src/lib.rs
> +        rio::ioctl_fionbio(&socket, true)?;
It's not clear if FIONBIO will work on all of these platforms.
https://github.com/smol-rs/async-process/pull/31#discussion_r1059236747
https://stackoverflow.com/a/1151077

For now, I think it's preferable to use it only on linux and windows, like [PR 111](https://github.com/smol-rs/async-io/pull/111/files#diff-b1a35a68f14e696205874893c07fd24fdb88882b47c23cc0e0c80a30c7d53759R1995-R2015).

2023-09-07 11:46 UTC, taiki-e commented on src/lib.rs
> +    ))]
AFAIK, NetBSD also supports nosigpipe (OpenBSD ~~and DragonflyBSD~~ do not).
- SO_NOSIGPIPE https://man.netbsd.org/setsockopt.2
- SOCK_NOSIGPIPE  https://man.netbsd.org/socket.2

Also, do you know why socket2 sets nosigpipe only on Apple targets, not also on FreeBSD/NetBSD?
https://github.com/rust-lang/socket2/blob/66ed6b055a4352a26ed25e8d01981fb5b555f3d8/src/socket.rs#L798
Maybe because MSG_NOSIGNAL has already been passed?
https://github.com/rust-lang/rust/blob/fece303aeb1d2b845745bc3c067475619670a868/library/std/src/sys_common/net.rs#L38

2023-09-07 11:53 UTC, taiki-e commented
> This doesn't set the inherit disable property on Windows yet, as rustix does not support it.

I think we can set HANDLE_FLAG_INHERIT by using [SetHandleInformation](https://learn.microsoft.com/en-us/windows/win32/api/handleapi/nf-handleapi-sethandleinformation) from windows-sys for now. (We already depend on windows-sys via polling and rustix.) Ideally, I would like to set that at the time the socket is created (i.e., by using SocketFlags).

2023-09-08 04:22 UTC, notgull commented on src/lib.rs
> +        ))]
According to `rustix` it doesn't exist there: https://docs.rs/rustix/latest/rustix/net/struct.SocketFlags.html#associatedconstant.CLOEXEC

2023-09-08 05:38 UTC, taiki-e commented on src/lib.rs
> +        ))]
> According to rustix it doesn't exist there: https://docs.rs/rustix/latest/rustix/net/struct.SocketFlags.html#associatedconstant.CLOEXEC

It's `SocketFlags`, which passed to `socket_with`. 

As for `FdFlags::CLOEXEC` (which passed to `fcntl_setfd`), it seems `rustix` provides it on all non-windows systems.
https://github.com/bytecodealliance/rustix/blob/7f3c973e7ae762a9e5133907a0d94a91c18d03ff/src/backend/libc/io/types.rs#L13
https://github.com/bytecodealliance/rustix/blob/7f3c973e7ae762a9e5133907a0d94a91c18d03ff/src/backend/libc/io/mod.rs#L2

2023-09-13 18:49 UTC, ivmarkov requested changes

2023-09-13 18:49 UTC, ivmarkov commented on src/lib.rs
> +            target_os = "haiku"
ESP-IDF also does not support `CLOEXEC`, so `target_os = "espidf"` needs to be listed here.

2023-09-13 18:49 UTC, ivmarkov commented on src/lib.rs
> +        ))]
Ditto.

2023-09-30 21:54 UTC, notgull commented on src/lib.rs
> +    ))]
I don't know, I would bet that it's because FreeBSD/NetBSD did not have it at the time.

2023-10-01 07:24 UTC, ivmarkov requested changes

2023-10-01 07:24 UTC, ivmarkov commented on src/lib.rs
> +            target_os = "esp-idf",
Should be `target_os = "espidf"`.

2023-10-01 07:24 UTC, ivmarkov commented on src/lib.rs
> +            target_os = "esp-idf",
Ditto.

2023-10-07 14:08 UTC, taiki-e commented on src/lib.rs
> -        target_os = "openbsd"
OpenBSD supports both SOCK_CLOEXEC and SOCK_NONBLOCK.
https://github.com/openbsd/src/blob/52154eb4e7fd31c059061300c34c89113e374244/sys/sys/socket.h#L76-L77

2023-10-07 23:21 UTC, notgull commented
The OpenBSD test failure is https://github.com/rust-lang/rust/issues/116523 combined with https://github.com/bytecodealliance/rustix/issues/869

2023-10-08 04:04 UTC, notgull commented
I've worked around this issue by disabling `uds_socket` on OpenBSD for now.

2023-10-08 04:11 UTC, taiki-e approved these changes

2023-10-08 04:18 UTC, merged

2023-10-08 15:46 UTC, taiki-e commented on src/lib.rs
> +    ))]
Opened https://github.com/bytecodealliance/rustix/pull/870 for NetBSD and DragonFlyBSD.