Add interval api.
smol-rs/async-io pull request #41
Opened 2020-11-20 15:20 UTC by dvc94ch

Based on #35, needed to use async-io in more places in libp2p.

2020-11-20 15:24 UTC, dvc94ch commented
Looks like ci is having issues

2020-11-23 10:57 UTC, dvc94ch commented
@stjepang any comments? It's currently blocking a PR of mine.

2020-11-25 19:14 UTC, stjepang requested changes
Thanks for implementing this! The PR looks good, I would just request the following changes:

1. Implement `poll()` by calling `poll_next()`. Treat a regular timer (`at()`/`after()`) as a stream (`interval_at()`) with a period of infinity.
2. Add a unit test to tests/timer.rs

2020-11-26 12:18 UTC, dvc94ch commented
Not sure how to construct an infinite `Duration`. Is 100y infinite enough?

2020-11-26 17:21 UTC, stjepang commented
Why is the first tick of a timer constructed by `interval()` immediate? `setInterval()` in javscript and `Ticker` in Go don't fire immediately, so I'm inclined to follow the same behavior here...

2020-11-26 19:14 UTC, dvc94ch commented
I guess that is what the start is for no? When periodically performing a process, usually you want to do it now too. Also this matches the behaviour of `wasm-timer`.

2020-11-27 16:33 UTC, dvc94ch commented
I think I agree, you can easily get the first tick with `Timer::interval_at(Instant::now(), period)`

2020-11-28 19:53 UTC, stjepang approved these changes
Thank you!

2020-11-28 19:54 UTC, merged

2020-11-28 20:02 UTC, dvc94ch commented
Can you release 1.2.1? Then I can update my PR's to libp2p.